-- Unable to render TABLE DDL for object GTD8.CONCELHOS with DBMS_METADATA attempting internal generator.
CREATE TABLE GTD8.CONCELHOS 
(
  COD NUMBER(4, 0) 
, DESIGNACAO VARCHAR2(50 BYTE) 
, DISTRITO NUMBER(4, 0) 
, REGIAO NUMBER(4, 0) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
