-- Unable to render TABLE DDL for object GTD8.RECINTOS with DBMS_METADATA attempting internal generator.
CREATE TABLE GTD8.RECINTOS 
(
  ID NUMBER(4, 0) 
, NOME VARCHAR2(80 BYTE) 
, LOTACAO NUMBER(8, 0) 
, TIPO NUMBER(4, 0) 
, MORADA VARCHAR2(80 BYTE) 
, CONCELHO NUMBER(4, 0) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
