-- Unable to render TABLE DDL for object GTD8.REGIOES with DBMS_METADATA attempting internal generator.
CREATE TABLE GTD8.REGIOES 
(
  COD NUMBER(4, 0) 
, DESIGNACAO VARCHAR2(50 BYTE) 
, NUT1 VARCHAR2(50 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
