-- 1)
/*X*/
SELECT XUCS.CODIGO, DESIGNACAO, XOCORRENCIAS.ANO_LETIVO, INSCRITOS,  TIPO, TURNOS
FROM XUCS
JOIN XOCORRENCIAS
    ON XUCS.CODIGO = XOCORRENCIAS.CODIGO
JOIN XTIPOSAULA
    ON (XUCS.CODIGO = XTIPOSAULA.CODIGO
    AND XTIPOSAULA.ANO_LETIVO = XOCORRENCIAS.ANO_LETIVO
    AND XTIPOSAULA.PERIODO = XOCORRENCIAS.PERIODO)
WHERE XUCS.DESIGNACAO = 'Bases de Dados'
    AND XUCS.CURSO = 275;

/*Y*/
SELECT YUCS.CODIGO, DESIGNACAO,YOCORRENCIAS.ANO_LETIVO, INSCRITOS,  TIPO, TURNOS
FROM YUCS
JOIN YOCORRENCIAS
    ON YUCS.CODIGO = YOCORRENCIAS.CODIGO
JOIN YTIPOSAULA
    ON (YUCS.CODIGO = YTIPOSAULA.CODIGO
    AND YTIPOSAULA.ANO_LETIVO = YOCORRENCIAS.ANO_LETIVO
    AND YTIPOSAULA.PERIODO = YOCORRENCIAS.PERIODO)
WHERE YUCS.DESIGNACAO = 'Bases de Dados'
    AND YUCS.CURSO = 275;

/*Z*/   
SELECT ZUCS.CODIGO, DESIGNACAO,ZOCORRENCIAS.ANO_LETIVO, INSCRITOS,  TIPO, TURNOS
FROM ZUCS
JOIN ZOCORRENCIAS
    ON ZUCS.CODIGO = ZOCORRENCIAS.CODIGO
JOIN ZTIPOSAULA
    ON (ZUCS.CODIGO = ZTIPOSAULA.CODIGO
    AND ZTIPOSAULA.ANO_LETIVO = ZOCORRENCIAS.ANO_LETIVO
    AND ZTIPOSAULA.PERIODO = ZOCORRENCIAS.PERIODO)
WHERE ZUCS.DESIGNACAO = 'Bases de Dados'
    AND ZUCS.CURSO = 275;
   
-- 2)
/*X*/
SELECT TIPO, SUM(HORAS_TURNO * TURNOS) 
FROM XTIPOSAULA
JOIN XOCORRENCIAS
    ON (XOCORRENCIAS.CODIGO = XTIPOSAULA.CODIGO
    AND XOCORRENCIAS.ANO_LETIVO = XTIPOSAULA.ANO_LETIVO
    AND XOCORRENCIAS.PERIODO = XTIPOSAULA.PERIODO)
JOIN XUCS 
    ON XTIPOSAULA.CODIGO = XUCS.CODIGO
WHERE XTIPOSAULA.ANO_LETIVO = '2004/2005'
    AND XUCS.CURSO = 233
GROUP BY TIPO;

/*Y*/
SELECT TIPO, SUM(HORAS_TURNO * TURNOS) 
FROM YTIPOSAULA
JOIN YOCORRENCIAS
    ON (YOCORRENCIAS.CODIGO = YTIPOSAULA.CODIGO
    AND YOCORRENCIAS.ANO_LETIVO = YTIPOSAULA.ANO_LETIVO
    AND YOCORRENCIAS.PERIODO = YTIPOSAULA.PERIODO)
JOIN YUCS 
    ON YTIPOSAULA.CODIGO = YUCS.CODIGO
WHERE YTIPOSAULA.ANO_LETIVO = '2004/2005'
    AND YUCS.CURSO = 233
GROUP BY TIPO;

/*Z*/
SELECT TIPO, SUM(HORAS_TURNO * TURNOS) 
FROM ZTIPOSAULA
JOIN ZOCORRENCIAS
    ON (ZOCORRENCIAS.CODIGO = ZTIPOSAULA.CODIGO
    AND ZOCORRENCIAS.ANO_LETIVO = ZTIPOSAULA.ANO_LETIVO
    AND ZOCORRENCIAS.PERIODO = ZTIPOSAULA.PERIODO)
JOIN ZUCS 
    ON ZTIPOSAULA.CODIGO = ZUCS.CODIGO
WHERE ZTIPOSAULA.ANO_LETIVO = '2004/2005'
    AND ZUCS.CURSO = 233
GROUP BY TIPO;

--3a
/*X*/
SELECT DISTINCT XUCS.CODIGO
FROM XUCS 
JOIN XOCORRENCIAS
ON XOCORRENCIAS.CODIGO = XUCS.CODIGO
WHERE ANO_LETIVO = '2003/2004'
    AND XUCS.CODIGO NOT IN
        (SELECT DISTINCT CODIGO
        FROM XTIPOSAULA
        JOIN XDSD
        ON XTIPOSAULA.ID = XDSD.ID
        WHERE ANO_LETIVO = '2003/2004');

/*Y*/
SELECT DISTINCT YUCS.CODIGO
FROM YUCS 
JOIN YOCORRENCIAS
ON YOCORRENCIAS.CODIGO = YUCS.CODIGO
WHERE ANO_LETIVO = '2003/2004'
    AND YUCS.CODIGO NOT IN
        (SELECT DISTINCT CODIGO
        FROM YTIPOSAULA
        JOIN YDSD
        ON YTIPOSAULA.ID = YDSD.ID
        WHERE ANO_LETIVO = '2003/2004');

/*Z*/        
SELECT DISTINCT ZUCS.CODIGO
FROM ZUCS 
JOIN ZOCORRENCIAS
ON ZOCORRENCIAS.CODIGO = ZUCS.CODIGO
WHERE ANO_LETIVO = '2003/2004'
    AND ZUCS.CODIGO NOT IN
        (SELECT DISTINCT CODIGO
        FROM ZTIPOSAULA
        JOIN ZDSD
        ON ZTIPOSAULA.ID = ZDSD.ID
        WHERE ANO_LETIVO = '2003/2004');
		
--3b
/*X*/
CREATE OR REPLACE VIEW CODIGOS AS
SELECT DISTINCT CODIGO
FROM XTIPOSAULA
JOIN XDSD
ON XTIPOSAULA.ID = XDSD.ID
WHERE ANO_LETIVO = '2003/2004';
        
SELECT DISTINCT XUCS.CODIGO
FROM XUCS 
JOIN XOCORRENCIAS
ON XOCORRENCIAS.CODIGO = XUCS.CODIGO 
AND ANO_LETIVO='2003/2004'
FULL OUTER JOIN CODIGOS  
ON CODIGOS.CODIGO=XUCS.CODIGO
WHERE CODIGOS.CODIGO IS NULL AND XUCS.CODIGO IS NOT NULL;

/*Y*/
CREATE OR REPLACE VIEW CODIGOS AS
SELECT DISTINCT CODIGO
FROM YTIPOSAULA
JOIN YDSD
ON YTIPOSAULA.ID = YDSD.ID
WHERE ANO_LETIVO = '2003/2004';
        
SELECT DISTINCT YUCS.CODIGO
FROM YUCS 
JOIN YOCORRENCIAS
ON YOCORRENCIAS.CODIGO = YUCS.CODIGO 
AND ANO_LETIVO='2003/2004'
FULL OUTER JOIN CODIGOS  
ON CODIGOS.CODIGO=YUCS.CODIGO
WHERE CODIGOS.CODIGO IS NULL AND YUCS.CODIGO IS NOT NULL;

/*Z*/
CREATE OR REPLACE VIEW CODIGOS AS
SELECT DISTINCT CODIGO
FROM ZTIPOSAULA
JOIN ZDSD
ON ZTIPOSAULA.ID = ZDSD.ID
WHERE ANO_LETIVO = '2003/2004';
        
SELECT DISTINCT ZUCS.CODIGO
FROM ZUCS 
JOIN ZOCORRENCIAS
ON ZOCORRENCIAS.CODIGO = ZUCS.CODIGO 
AND ANO_LETIVO='2003/2004'
FULL OUTER JOIN CODIGOS  
ON CODIGOS.CODIGO=ZUCS.CODIGO
WHERE CODIGOS.CODIGO IS NULL AND ZUCS.CODIGO IS NOT NULL;

--4
/*X*/
CREATE OR REPLACE VIEW HORAS_POR_PROF AS
SELECT XDOCENTES.NR, NOME, TIPO, SUM(HORAS * FATOR) AS TOTAL
FROM XDOCENTES
JOIN XDSD
    ON XDSD.NR = XDOCENTES.NR
JOIN XTIPOSAULA
    ON XTIPOSAULA.ID = XDSD.ID
WHERE XTIPOSAULA.ANO_LETIVO = '2003/2004'
GROUP BY XDOCENTES.NR, NOME, TIPO;

CREATE OR REPLACE VIEW MAX_HORAS_TIPO AS
SELECT TIPO, MAX(TOTAL) AS MAXIMO
FROM HORAS_POR_PROF
GROUP BY TIPO;

SELECT NR, NOME, MAX_HORAS_TIPO.TIPO, MAX_HORAS_TIPO.MAXIMO AS TOTAL
FROM HORAS_POR_PROF
JOIN MAX_HORAS_TIPO
    ON (MAX_HORAS_TIPO.TIPO = HORAS_POR_PROF.TIPO
    AND MAX_HORAS_TIPO.MAXIMO = HORAS_POR_PROF.TOTAL);
	
/*Y*/
CREATE OR REPLACE VIEW HORAS_POR_PROF AS
SELECT YDOCENTES.NR, NOME, TIPO, SUM(HORAS * FATOR) AS TOTAL
FROM YDOCENTES
JOIN YDSD
    ON YDSD.NR = YDOCENTES.NR
JOIN YTIPOSAULA
    ON YTIPOSAULA.ID = YDSD.ID
WHERE YTIPOSAULA.ANO_LETIVO = '2003/2004'
GROUP BY YDOCENTES.NR, NOME, TIPO;

CREATE OR REPLACE VIEW MAX_HORAS_TIPO AS
SELECT TIPO, MAX(TOTAL) AS MAXIMO
FROM HORAS_POR_PROF
GROUP BY TIPO;

SELECT NR, NOME, MAX_HORAS_TIPO.TIPO, MAX_HORAS_TIPO.MAXIMO AS TOTAL
FROM HORAS_POR_PROF
JOIN MAX_HORAS_TIPO
    ON (MAX_HORAS_TIPO.TIPO = HORAS_POR_PROF.TIPO
    AND MAX_HORAS_TIPO.MAXIMO = HORAS_POR_PROF.TOTAL);
	
/*Z*/
CREATE OR REPLACE VIEW HORAS_POR_PROF AS
SELECT ZDOCENTES.NR, NOME, TIPO, SUM(HORAS * FATOR) AS TOTAL
FROM ZDOCENTES
JOIN ZDSD
    ON ZDSD.NR = ZDOCENTES.NR
JOIN ZTIPOSAULA
    ON ZTIPOSAULA.ID = ZDSD.ID
WHERE ZTIPOSAULA.ANO_LETIVO = '2003/2004'
GROUP BY ZDOCENTES.NR, NOME, TIPO;

CREATE OR REPLACE VIEW MAX_HORAS_TIPO AS
SELECT TIPO, MAX(TOTAL) AS MAXIMO
FROM HORAS_POR_PROF
GROUP BY TIPO;

SELECT NR, NOME, MAX_HORAS_TIPO.TIPO, MAX_HORAS_TIPO.MAXIMO AS TOTAL
FROM HORAS_POR_PROF
JOIN MAX_HORAS_TIPO
    ON (MAX_HORAS_TIPO.TIPO = HORAS_POR_PROF.TIPO
    AND MAX_HORAS_TIPO.MAXIMO = HORAS_POR_PROF.TOTAL);

--5a
/*X*/
DROP INDEX IX_XTIPOSAULA_TIPO_ANOLETIVO;
CREATE INDEX IX_XTIPOSAULA_TIPO_ANOLETIVO ON XTIPOSAULA (TIPO,ANO_LETIVO);

SELECT XOCORRENCIAS.CODIGO, XOCORRENCIAS.ANO_LETIVO, XOCORRENCIAS.PERIODO, XTIPOSAULA.TURNOS * XTIPOSAULA.HORAS_TURNO AS NUMBER_OF_HOURS
    FROM XOCORRENCIAS
        JOIN XTIPOSAULA
            ON XOCORRENCIAS.CODIGO = XTIPOSAULA.CODIGO
                AND XOCORRENCIAS.ANO_LETIVO = XTIPOSAULA.ANO_LETIVO 
    WHERE (XTIPOSAULA.ANO_LETIVO = '2002/2003'
        OR XTIPOSAULA.ANO_LETIVO = '2003/2004')
        AND XTIPOSAULA.TIPO = 'OT';
        
/*Y*/
SELECT YOCORRENCIAS.CODIGO, YOCORRENCIAS.ANO_LETIVO, YOCORRENCIAS.PERIODO, YTIPOSAULA.TURNOS * YTIPOSAULA.HORAS_TURNO AS NUMBER_OF_HOURS
    FROM YOCORRENCIAS
        JOIN YTIPOSAULA
            ON YOCORRENCIAS.CODIGO = YTIPOSAULA.CODIGO
                AND YOCORRENCIAS.ANO_LETIVO = YTIPOSAULA.ANO_LETIVO 
    WHERE (YTIPOSAULA.ANO_LETIVO = '2002/2003'
        OR YTIPOSAULA.ANO_LETIVO = '2003/2004')
        AND YTIPOSAULA.TIPO = 'OT';
        
/*Z*/
SELECT ZOCORRENCIAS.CODIGO, ZOCORRENCIAS.ANO_LETIVO, ZOCORRENCIAS.PERIODO, ZTIPOSAULA.TURNOS * ZTIPOSAULA.HORAS_TURNO AS NUMBER_OF_HOURS
    FROM ZOCORRENCIAS
        JOIN ZTIPOSAULA
            ON ZOCORRENCIAS.CODIGO = ZTIPOSAULA.CODIGO
                AND ZOCORRENCIAS.ANO_LETIVO = ZTIPOSAULA.ANO_LETIVO 
    WHERE (ZTIPOSAULA.ANO_LETIVO = '2002/2003'
        OR ZTIPOSAULA.ANO_LETIVO = '2003/2004')
        AND ZTIPOSAULA.TIPO = 'OT';
		
--5b
/*X*/
DROP INDEX IX_XTIPOSAULA_TIPO_ANOLETIVO;
CREATE BITMAP INDEX IX_XTIPOSAULA_TIPO_ANOLETIVO ON XTIPOSAULA (TIPO,ANO_LETIVO);

SELECT XOCORRENCIAS.CODIGO, XOCORRENCIAS.ANO_LETIVO, XOCORRENCIAS.PERIODO, XTIPOSAULA.TURNOS * XTIPOSAULA.HORAS_TURNO AS NUMBER_OF_HOURS
    FROM XOCORRENCIAS
        JOIN XTIPOSAULA
            ON XOCORRENCIAS.CODIGO = XTIPOSAULA.CODIGO
                AND XOCORRENCIAS.ANO_LETIVO = XTIPOSAULA.ANO_LETIVO
    WHERE (XTIPOSAULA.ANO_LETIVO = '2002/2003'
        OR XTIPOSAULA.ANO_LETIVO = '2003/2004')
        AND XTIPOSAULA.TIPO = 'OT';

/*Y*/
SELECT YOCORRENCIAS.CODIGO, YOCORRENCIAS.ANO_LETIVO, YOCORRENCIAS.PERIODO, YTIPOSAULA.TURNOS * YTIPOSAULA.HORAS_TURNO AS NUMBER_OF_HOURS
    FROM YOCORRENCIAS
        JOIN YTIPOSAULA
            ON YOCORRENCIAS.CODIGO = YTIPOSAULA.CODIGO
                AND YOCORRENCIAS.ANO_LETIVO = YTIPOSAULA.ANO_LETIVO 
    WHERE (YTIPOSAULA.ANO_LETIVO = '2002/2003'
        OR YTIPOSAULA.ANO_LETIVO = '2003/2004')
        AND YTIPOSAULA.TIPO = 'OT';
        
/*Z*/
SELECT ZOCORRENCIAS.CODIGO, ZOCORRENCIAS.ANO_LETIVO, ZOCORRENCIAS.PERIODO, ZTIPOSAULA.TURNOS * ZTIPOSAULA.HORAS_TURNO AS NUMBER_OF_HOURS
    FROM ZOCORRENCIAS
        JOIN ZTIPOSAULA
            ON ZOCORRENCIAS.CODIGO = ZTIPOSAULA.CODIGO
                AND ZOCORRENCIAS.ANO_LETIVO = ZTIPOSAULA.ANO_LETIVO 
    WHERE (ZTIPOSAULA.ANO_LETIVO = '2002/2003'
        OR ZTIPOSAULA.ANO_LETIVO = '2003/2004')
        AND ZTIPOSAULA.TIPO = 'OT';
		
--6
/*X*/
SELECT DISTINCT XUCS.CURSO
    FROM XUCS
    WHERE 
        (EXISTS(
            SELECT XTIPOSAULA.ID 
            FROM XTIPOSAULA 
            WHERE XTIPOSAULA.TIPO='P' 
                AND XUCS.CODIGO=XTIPOSAULA.CODIGO)
        AND EXISTS(
            SELECT XTIPOSAULA.ID 
            FROM XTIPOSAULA 
            WHERE XTIPOSAULA.TIPO='TP' 
                AND XUCS.CODIGO=XTIPOSAULA.CODIGO)
        AND EXISTS(
            SELECT XTIPOSAULA.ID 
            FROM XTIPOSAULA 
            WHERE XTIPOSAULA.TIPO='T' 
                AND XUCS.CODIGO=XTIPOSAULA.CODIGO)
        AND EXISTS(
            SELECT XTIPOSAULA.ID 
            FROM XTIPOSAULA 
            WHERE XTIPOSAULA.TIPO='L' 
                AND XUCS.CODIGO=XTIPOSAULA.CODIGO)
        AND EXISTS(
            SELECT XTIPOSAULA.ID 
            FROM XTIPOSAULA 
            WHERE XTIPOSAULA.TIPO='OT' 
                AND XUCS.CODIGO=XTIPOSAULA.CODIGO)
        );
        
/*Y*/
SELECT DISTINCT YUCS.CURSO
    FROM YUCS
    WHERE 
        (EXISTS(
            SELECT YTIPOSAULA.ID 
            FROM YTIPOSAULA 
            WHERE YTIPOSAULA.TIPO='P' 
                AND YUCS.CODIGO=YTIPOSAULA.CODIGO)
        AND EXISTS(
            SELECT YTIPOSAULA.ID 
            FROM YTIPOSAULA 
            WHERE YTIPOSAULA.TIPO='TP' 
                AND YUCS.CODIGO=YTIPOSAULA.CODIGO)
        AND EXISTS(
            SELECT YTIPOSAULA.ID 
            FROM YTIPOSAULA 
            WHERE YTIPOSAULA.TIPO='T' 
                AND YUCS.CODIGO=YTIPOSAULA.CODIGO)
        AND EXISTS(
            SELECT YTIPOSAULA.ID 
            FROM YTIPOSAULA 
            WHERE YTIPOSAULA.TIPO='L' 
                AND YUCS.CODIGO=YTIPOSAULA.CODIGO)
        AND EXISTS(
            SELECT YTIPOSAULA.ID 
            FROM YTIPOSAULA 
            WHERE YTIPOSAULA.TIPO='OT' 
                AND YUCS.CODIGO=YTIPOSAULA.CODIGO)
        );
        
/*Z*/
SELECT DISTINCT ZUCS.CURSO
    FROM ZUCS
    WHERE 
        (EXISTS(
            SELECT ZTIPOSAULA.ID 
            FROM ZTIPOSAULA 
            WHERE ZTIPOSAULA.TIPO='P' 
                AND ZUCS.CODIGO=ZTIPOSAULA.CODIGO)
        AND EXISTS(
            SELECT ZTIPOSAULA.ID 
            FROM ZTIPOSAULA 
            WHERE ZTIPOSAULA.TIPO='TP' 
                AND ZUCS.CODIGO=ZTIPOSAULA.CODIGO)
        AND EXISTS(
            SELECT ZTIPOSAULA.ID 
            FROM ZTIPOSAULA 
            WHERE ZTIPOSAULA.TIPO='T' 
                AND ZUCS.CODIGO=ZTIPOSAULA.CODIGO)
        AND EXISTS(
            SELECT ZTIPOSAULA.ID 
            FROM ZTIPOSAULA 
            WHERE ZTIPOSAULA.TIPO='L' 
                AND ZUCS.CODIGO=ZTIPOSAULA.CODIGO)
        AND EXISTS(
            SELECT ZTIPOSAULA.ID 
            FROM ZTIPOSAULA 
            WHERE ZTIPOSAULA.TIPO='OT' 
                AND ZUCS.CODIGO=ZTIPOSAULA.CODIGO)
        );