/*  DROP ALL TABLES */

DROP TABLE XDOCENTES;
DROP TABLE XDSD;
DROP TABLE XOCORRENCIAS;
DROP TABLE XTIPOSAULA;
DROP TABLE XUCS;
DROP TABLE YDOCENTES;
DROP TABLE YDSD;
DROP TABLE YOCORRENCIAS;
DROP TABLE YTIPOSAULA;
DROP TABLE YUCS;
DROP TABLE ZDOCENTES;
DROP TABLE ZDSD;
DROP TABLE ZOCORRENCIAS;
DROP TABLE ZTIPOSAULA;
DROP TABLE ZUCS;


/* CREATE ALL TABLES */

CREATE TABLE XDOCENTES AS
SELECT * 
FROM   GTD10.XDOCENTES;

CREATE TABLE XDSD AS
SELECT * 
FROM   GTD10.XDSD;

CREATE TABLE XTIPOSAULA AS
SELECT * 
FROM   GTD10.XTIPOSAULA;

CREATE TABLE XOCORRENCIAS AS
SELECT * 
FROM   GTD10.XOCORRENCIAS;

CREATE TABLE XUCS AS
SELECT * 
FROM   GTD10.XUCS;

CREATE TABLE YDOCENTES AS
SELECT * 
FROM   GTD10.XDOCENTES;

CREATE TABLE YDSD AS
SELECT * 
FROM   GTD10.XDSD;

CREATE TABLE YTIPOSAULA AS
SELECT * 
FROM   GTD10.XTIPOSAULA;

CREATE TABLE YOCORRENCIAS AS
SELECT * 
FROM   GTD10.XOCORRENCIAS;

CREATE TABLE YUCS AS
SELECT * 
FROM   GTD10.XUCS;

CREATE TABLE ZDOCENTES AS
SELECT * 
FROM   GTD10.XDOCENTES;

CREATE TABLE ZDSD AS
SELECT * 
FROM   GTD10.XDSD;

CREATE TABLE ZTIPOSAULA AS
SELECT * 
FROM   GTD10.XTIPOSAULA;

CREATE TABLE ZOCORRENCIAS AS
SELECT * 
FROM   GTD10.XOCORRENCIAS;

CREATE TABLE ZUCS AS
SELECT * 
FROM   GTD10.XUCS;


/* ADD PRIMARY KEYS */

ALTER TABLE YDOCENTES
ADD PRIMARY KEY (NR);

ALTER TABLE YDSD
ADD PRIMARY KEY (NR, ID);

ALTER TABLE YTIPOSAULA
ADD PRIMARY KEY (ID);

ALTER TABLE YOCORRENCIAS
ADD PRIMARY KEY (CODIGO, ANO_LETIVO, PERIODO);

ALTER TABLE YUCS
ADD PRIMARY KEY (CODIGO);

ALTER TABLE ZDOCENTES
ADD PRIMARY KEY (NR);

ALTER TABLE ZDSD
ADD PRIMARY KEY (NR, ID);

ALTER TABLE ZTIPOSAULA
ADD PRIMARY KEY (ID);

ALTER TABLE ZOCORRENCIAS
ADD PRIMARY KEY (CODIGO, ANO_LETIVO, PERIODO);

ALTER TABLE ZUCS
ADD PRIMARY KEY (CODIGO);

/* ADD FOREIGN KEYS */

ALTER TABLE YDSD
ADD FOREIGN KEY (NR) REFERENCES YDOCENTES(NR); 

ALTER TABLE YDSD
ADD FOREIGN KEY (ID) REFERENCES YTIPOSAULA(ID);

ALTER TABLE YTIPOSAULA
ADD FOREIGN KEY (ANO_LETIVO, PERIODO, CODIGO) REFERENCES YOCORRENCIAS(ANO_LETIVO, PERIODO, CODIGO) NOVALIDATE;

ALTER TABLE YOCORRENCIAS
ADD FOREIGN KEY (CODIGO) REFERENCES YUCS(CODIGO);

ALTER TABLE ZDSD
ADD FOREIGN KEY (NR) REFERENCES ZDOCENTES(NR); 

ALTER TABLE ZDSD
ADD FOREIGN KEY (ID) REFERENCES ZTIPOSAULA(ID);

ALTER TABLE ZTIPOSAULA
ADD FOREIGN KEY (ANO_LETIVO, PERIODO, CODIGO) REFERENCES ZOCORRENCIAS(ANO_LETIVO, PERIODO, CODIGO) NOVALIDATE;

ALTER TABLE ZOCORRENCIAS
ADD FOREIGN KEY (CODIGO) REFERENCES ZUCS(CODIGO);

/* INDEXES */

DROP INDEX IX_ZUCS_DESIGNACAO_CURSO;
CREATE INDEX IX_ZUCS_DESIGNACAO_CURSO
ON ZUCS(DESIGNACAO, CURSO);

DROP INDEX IX_ZTIPOSAULA_CODIGO_ANOLETIVO_PERIODO;
CREATE INDEX IX_ZTIPOSAULA_CODIGO_ANOLETIVO_PERIODO
ON ZTIPOSAULA(CODIGO, ANO_LETIVO, PERIODO);

DROP INDEX IX_ZTIPOSAULA_ANOLETIVO;
CREATE INDEX IX_ZTIPOSAULA_ANOLETIVO
ON ZTIPOSAULA(ANO_LETIVO);

DROP INDEX IX_ZUCS_CURSO;
CREATE BITMAP INDEX IX_ZUCS_CURSO
ON ZUCS(CURSO);

DROP INDEX IX_ZDSD_ID;
CREATE INDEX IX_ZDSD_ID
ON ZDSD(ID);

DROP INDEX IX_ZTIPOSAULA_TIPO;
CREATE INDEX IX_ZTIPOSAULA_TIPO
ON ZTIPOSAULA(TIPO);

DROP INDEX IX_ZTIPOSAULA_TIPO_ANOLETIVO;
CREATE INDEX IX_ZTIPOSAULA_TIPO_ANOLETIVO
ON ZTIPOSAULA(TIPO, ANO_LETIVO);